---

- hosts: web
  roles:
     - { role: 'common' }
     - { role: 'hostname', new_hostname: "lf-stage" }

- hosts: db
  roles:
     - { role: 'common' }
     - { role: 'hostname', new_hostname: "lf-stage" }